#!/bin/bash

#git clone git://git.qemu-project.org/qemu.git
cd qemu
git submodule init
git submodule update --recursive
git submodule status --recursive
git checkout stable-2.9
mkdir cloudskulk-build
cd cloudskulk-build
sudo dnf install glib* zlib-devel gcc-c++ gtk2-devel libfdt-devel
../configure
make -j4


